name: equivariant
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.8.5
  - pip=20.3
  - pytorch-cuda=11.8
  - pytorch=2.2.2
  - torchvision=0.17.2
  - numpy=1.22
  - pip:
    - timm==0.9.12
    - tensorboard==2.10.0
    - scipy==1.9.1
    - gdown==5.2.0
    - -e git+https://github.com/LTH14/torch-fidelity.git@master#egg=torch-fidelity
    - clip
    - omegaconf==2.1.1
    - pytorch_lightning==1.4.2
    - torchmetrics==0.5.0 
    - test-tube
    - albumentations
    - kornia 
    - matplotlib 
    - einops
    - diffusers
